// pages/terms.jsx
import React from 'react'

export default function TermsAndConditions() {
  return (
    <div className="min-h-screen bg-gray-50 py-16">
      <div className="max-w-3xl mx-auto bg-white shadow-lg rounded-lg p-8">
        <h1 className="text-3xl font-bold mb-6">Terms &amp; Conditions for KarsutraHQ</h1>

        <p className="mb-4">
          This document is an electronic record in terms of the Information Technology Act, 2000 and rules thereunder as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
        </p>

        <p className="mb-6">
          This document is published in accordance with the provisions of Rule 3(1)(a) of the Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021, the Information Technology (Intermediaries Guidelines) Rules, 2011, and Rule 4 of the Information Technology (Reasonable Security Practices and Procedures and Sensitive Personal Data or Information) Rules, 2011, framed under the Information Technology Act, 2000 (as amended). It requires publishing the rules and regulations, Privacy Policy, and Terms of Use for access or usage of the Platform at{' '}
          <a href="https://karsutrahq.com" className="text-blue-600 hover:underline">
            https://karsutrahq.com
          </a>.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">1. Definitions &amp; Interpretation</h2>
        <p className="mb-4">
          <strong>“Platform”</strong> refers to https://karsutrahq.com and its subdomains, mobile apps, and any other channels through which KarsutraHQ provides its services.  
          <strong>“Services”</strong> means the products and tax consultancy, filing, accounting, and related services offered by KarsutraHQ via the Platform.  
          <strong>“You”</strong> or <strong>“Your”</strong> refers to the individual or entity using or accessing the Platform or Services.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">2. Acceptance of Terms</h2>
        <p className="mb-4">
          By accessing or using the Platform or Services, You agree to be bound by these Terms &amp; Conditions. If You do not agree, please discontinue your use of the Platform immediately.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">3. Eligibility</h2>
        <p className="mb-4">
          Use of the Platform and Services is available only to individuals who are Indian citizens or Non-Resident Indians, aged 18 or above, capable of entering into a legally binding contract, and not barred by any law.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">4. Modifications to Terms</h2>
        <p className="mb-4">
          KarsutraHQ reserves the right to modify, add, or remove portions of these Terms at any time without prior notice. Continued use of the Platform after changes are posted constitutes acceptance of the revised Terms.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">5. Service Description</h2>
        <p className="mb-4">
          KarsutraHQ provides tax filing, GST reconciliation, accounting &amp; bookkeeping, business registration, and financial consultancy services. We may modify or discontinue Services at our sole discretion.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">6. Your Obligations</h2>
        <p className="mb-4">
          You agree to provide accurate, up-to-date information when using our Services. You will not use automated scripts or bots, nor reproduce or resell the Platform or its content without express written permission.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">7. Refunds &amp; Cancellations</h2>
        <p className="mb-4">
          Either party may terminate Services at any time. Refunds for unused Services are at KarsutraHQ’s discretion and subject to applicable policies.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">8. Privacy</h2>
        <p className="mb-4">
          Your use of personal data on the Platform is governed by our{' '}
          <a href="/privacy" className="text-blue-600 hover:underline">
            Privacy Policy
          </a>.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">9. Limitation of Liability</h2>
        <p className="mb-4">
          To the extent permitted by law, KarsutraHQ and its affiliates shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the Platform or Services.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">10. Governing Law &amp; Dispute Resolution</h2>
        <p className="mb-4">
          These Terms are governed by the laws of India. Any dispute shall be subject to the exclusive jurisdiction of courts in Gurugram, Haryana.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">11. Contact Information</h2>
        <p>
          For any queries regarding these Terms, please write to us at{' '}
          <a href="mailto:support@karsutrahq.com" className="text-blue-600 hover:underline">
            support@karsutrahq.com
          </a> or visit our office at:<br />
          <span className="block mt-2 font-medium">
            4th Floor, ENKAY TOWER, Phase V, Udyog Vihar,<br />
            Sector 19, Gurugram, Haryana 122001
          </span>
        </p>
      </div>
    </div>
  )
}
